## Basic Operations

In [1]:
import numpy as np

In [2]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [3]:
a + 10

array([10, 11, 12, 13, 14])

In [4]:
a*3

array([ 0,  3,  6,  9, 12])

In [5]:
a**2

array([ 0,  1,  4,  9, 16], dtype=int32)

In [6]:
b = np.arange(2, 7)
b

array([2, 3, 4, 5, 6])

In [7]:
a + b

array([ 2,  4,  6,  8, 10])

In [8]:
b-a

array([2, 2, 2, 2, 2])

In [9]:
a**b

array([   0,    1,   16,  243, 4096], dtype=int32)

In [10]:
a*b**0.5

array([0.        , 1.73205081, 4.        , 6.70820393, 9.79795897])

## Matrix Product

In [11]:
np.dot(a, b)

50